version: '3'

services:
  socket-server:
    build: .
    container_name: socket-server
    ports:
      - "9001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docopypaste.rule=Host(`socket-server.cpypst.online`)"
      - "traefik.http.services.docopypaste.loadbalancer.server.port=9001"
      - "traefik.http.routers.docopypaste.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.docopypaste.tls=true"
    networks:
      - traefik-net
    env_file:
      - .env

networks:
  traefik-net:
    external: true
    